# ===========================================
# BASE DE CONOCIMIENTO COMPLETA (PARTE 1)
# Convertida desde Prolog a Python
# ===========================================

# ------------------------
# MATERIAS POR SEMESTRE
# ------------------------
materias = {
    'ALGEBRA': 'primer semestre',
    'CALCULO DIFERENCIAL E INTEGRAL': 'primer semestre',
    'COMPUTADORAS Y PROGRAMACION': 'primer semestre',
    'GEOMETRIA ANALITICA': 'primer semestre',
    'INTRODUCCION A LA INGENIERIA EN COMPUTACION': 'primer semestre',

    'ALGEBRA LINEAL': 'segundo semestre',
    'CALCULO VECTORIAL': 'segundo semestre',
    'COMUNICACION': 'segundo semestre',
    'EMPRENDIMIENTO 1': 'segundo semestre',
    'PROGRAMACION ORIENTADA A OBJETOS': 'segundo semestre',
    'TALLER DE CREATIVIDAD E INNOVACION': 'segundo semestre',

    'ECUACIONES DIFERENCIALES': 'tercer semestre',
    'ELECTRICIDAD Y MAGNETISMO (L)': 'tercer semestre',
    'EMPRENDIMIENTO 2': 'tercer semestre',
    'ESTRUCTURA DE DATOS': 'tercer semestre',
    'METODOS NUMERICOS': 'tercer semestre',

    'BASES DE DATOS 1': 'cuarto semestre',
    'DISPOSITIVOS ELECTRONICOS (L)': 'cuarto semestre',
    'EMPRENDIMIENTO 3': 'cuarto semestre',
    'MATEMATICAS DISCRETAS': 'cuarto semestre',
    'PROBABILIDAD Y ESTADISTICA': 'cuarto semestre',

    'ADMINISTRACION DE PROYECTOS': 'quinto semestre',
    'DISENO LOGICO (L)': 'quinto semestre',
    'DISENO Y ANALISIS DE ALGORITMOS': 'quinto semestre',
    'LENGUAJES FORMALES Y AUTOMATAS': 'quinto semestre',
    'PROGRAMACION WEB 1': 'quinto semestre',

    'COMPILADORES': 'sexto semestre',
    'DISENO DE SISTEMAS DIGITALES (L)': 'sexto semestre',
    'INGENIERIA DE SOFTWARE': 'sexto semestre',
    'SISTEMAS OPERATIVOS': 'sexto semestre',

    'MICROPROCESADORES Y MICROCONTROLADORES (L)': 'septimo semestre',
    'PROGRAMACION WEB 2': 'septimo semestre',
    'REDES DE COMPUTADORAS 1 (L)': 'septimo semestre',
    'SISTEMAS DE INFORMACION': 'septimo semestre',

    'BASES DE DATOS 2': 'octavo semestre',
    'HABILIDADES DIRECTIVAS': 'octavo semestre',
    'PROGRAMACION MOVIL 1': 'octavo semestre',
    'REDES DE COMPUTADORAS 2': 'octavo semestre',

    'INTELIGENCIA ARTIFICIAL': 'noveno semestre',
    'MINERIA DE DATOS': 'noveno semestre',
    'SEGURIDAD INFORMATICA': 'noveno semestre',
    'GRAFICACION POR COMPUTADORA': 'noveno semestre'
}

# ------------------------
# OPTATIVAS
# ------------------------
optativas = [
    'TEMAS ESPECIALES DE COMPUTACION 1',
    'TEMAS ESPECIALES DE COMPUTACION 2',
    'SEMINARIO INGENIERIA EN COMPUTACION',
    'ROBOTICA',
    'PROYECTO ESCUELA-INDUSTRIA',
    'LAB REDES DE COMPUTADORAS I',
    'TEMAS ESPECIALES DE COMPUTACION 4',
    'ADMINISTRACION SISTEMAS MULTIUSUAR',
    'INTERNET DE LAS COSAS',
    'PROCESAMIENTO DIGIT.IMAGENES',
    'TEMAS ESPECIALES DE SEGURIDAD INFORM',
    'TEMAS ESPECIALES DE BASES DE DATOS',
    'TEMAS ESPECIALES DE PROGRAMACION 2',
    'VINCULACION EMPRESARIAL',
    'TEMAS ESPECIALES DE REDES',
    'SISTEMAS EXPERTOS',
    'PROGRAMACION DE VIDEOJUEGOS 1',
    'PROGRAMACION DE VIDEOJUEGOS 2',
    'TEMAS ESPECIALES DE COMPUTACION 6',
    'TEMAS ESPECIALES DE COMPUTACION 3',
    'INSTRUMENTACION Y CONTROL'
]

# ------------------------
# PROFESORES Y MATERIAS QUE IMPARTEN
# ------------------------

# ------------------------
# PROFESORES Y MATERIAS QUE IMPARTEN
# ------------------------

profesores = {
    'ABURTO CAMACHO BLANCA PAMELA': ['TALLER DE CREATIVIDAD E INNOVACION'],
    'AGUILAR HERNANDEZ JOSE FRANCISCO': ['SEGURIDAD INFORMATICA'],
    'ALBA VILLA BELEN ANAID': ['ADMINISTRACION DE PROYECTOS'],
    'ALMANZAR VAZQUEZ MARIA GUADALUPE': ['COMUNICACION', 'TEMAS ESPECIALES DE COMPUTACION 1'],
    'ALVAREZ SORIANO MANUEL ALEJANDRO': ['ELECTRICIDAD Y MAGNETISMO (L)'],
    'ANAYA MANILA DZOARA IVETTE': ['REDES DE COMPUTADORAS 1 (L)'],
    'ARELLANO OROZCO JUAN MANUEL': ['INTRODUCCION A LA INGENIERIA EN COMPUTACION'],
    'ARELLANO RIVERA ESTEBAN': ['DISEÑO LOGICO (L)'],
    'AVILA GARCIA JOSE ANTONIO': ['TEMAS ESPECIALES DE COMPUTACION 2'],
    'AYALA PEÑA ESTEBAN': ['SISTEMAS OPERATIVOS'],
    'BERNAL DIAZ ARCELIA': ['DISEÑO LOGICO (L)', 'MICROPROCESADOR.Y MICROCONTROLAD.(L)'],
    'BLANCO BAUTISTA ROBERTO': ['ECUACIONES DIFERENCIALES', 'ESTRUCTURA DE DATOS', 'METODOS NUMERICOS'],
    'CAMACHO ALVAREZ JUAN CARLOS': ['DISEÑO Y ANALISIS DE ALGORITMOS', 'PROGRAMACION MOVIL 1', 'PROGRAMACION WEB 1'],
    'CAMPOS BRAVO JORGE IVAN': ['LENGUAJES FORMALES-AUTOMATAS'],
    'CANDELARIO ALAVEZ JORGE LUIS': [
        'COMPUTADORAS Y PROGRAMACION',
        'INTRODUCCION A LA INGENIERIA EN COMPUTACION',
        'MICROPROCESADOR.Y MICROCONTROLAD.(L)',
        'PROGRAMACION ORIENTADA A OBJETOS',
        'PROGRAMACION WEB 1',
        'SISTEMAS DE INFORMACION'
    ],
    'CANO SANTOS BERENICE': ['SEMINARIO INGENIERIA EN COMPUTACION'],
    'CANTO GALLO RAFAEL': ['MINERIA DE DATOS'],
    'CASTRO DIAZ JOSE DANIEL': ['ROBOTICA'],
    'CERVANTES PATIÑO MOISES': ['EMPRENDIMIENTO 3'],
    'CHIAPA MONROY CUAUHTEMOC': ['TALLER DE CREATIVIDAD E INNOVACION'],
    'COLUNGA VAZQUEZ MATILDE': ['EMPRENDIMIENTO 1', 'EMPRENDIMIENTO 2', 'PROYECTO ESCUELA-INDUSTRIA'],
    'COVARRUBIAS RODRIGUEZ FERNANDO ROBERTO': ['PROYECTO ESCUELA-INDUSTRIA'],
    'CRUZ LUEVANO BLANCA ESTELA': [
        'ESTRUCTURA DE DATOS',
        'INGENIERIA DE SOFTWARE',
        'PROGRAMACION ORIENTADA A OBJETOS',
        'SISTEMAS DE INFORMACION'
    ],
    'CRUZ ROSALES ERNESTO': ['PROYECTO ESCUELA-INDUSTRIA'],
    'DAVILA PEREZ RENE ADRIAN': ['LAB REDES DE COMPUTADORAS I'],
    'ESCONDRILLAS MAYA CARLOS': ['TEMAS ESPECIALES DE COMPUTACION 4'],
    'FALCON ARELLANO BERENICE ITZEL': ['ALGEBRA LINEAL'],
    'FERIA VICTORIA MARIA ANGELICA': ['EMPRENDIMIENTO 1', 'HABILIDADES DIRECTIVAS'],
    'FLORES DIAZ IMELDA DE LA LUZ': ['PROYECTO ESCUELA-INDUSTRIA', 'TEMAS ESPECIALES DE COMPUTACION 1'],
    'GALICIA RANGEL GILDA': ['REDES DE COMPUTADORAS 1 (L)'],
    'GARCIA GUZMAN ENRIQUE': ['INSTRUMENTACION Y CONTROL', 'REDES DE COMPUTADORAS 1 (L)', 'REDES DE COMPUTADORAS 2'],
    'GARCIA MONROY JOSE ANTONIO': ['REDES DE COMPUTADORAS 1 (L)', 'REDES DE COMPUTADORAS 2'],
    'GARCIA VILLANUEVA MA. DEL PILAR': ['EMPRENDIMIENTO 2', 'EMPRENDIMIENTO 3'],
    'GARIBAY PEDRAZA ALMA LILIA': ['HABILIDADES DIRECTIVAS'],
    'GASTALDI PEREZ JUAN': ['COMPUTADORAS Y PROGRAMACION'],
    'GERMAN ROSAS CESAR FRANCISCO': ['BASES DE DATOS 2', 'TEMAS ESPECIALES DE BASES DE DATOS'],
    'GONZALEZ AYALA LUIS ENRIQUE': ['ADMINISTRACION DE PROYECTOS', 'GRAFICACION POR COMPUTADORA'],
    'GONZALEZ BETANCOURT RAFAEL': ['ECUACIONES DIFERENCIALES', 'GEOMETRIA ANALITICA', 'METODOS NUMERICOS'],
    'GONZALEZ HERNANDEZ GERARDO': [
        'CALCULO DIFERENCIAL E INTEGRAL',
        'CALCULO VECTORIAL',
        'ECUACIONES DIFERENCIALES'
    ],
    'GONZALEZ HERNANDEZ MARIA GABRIELA': ['INGENIERIA DE SOFTWARE', 'SISTEMAS OPERATIVOS'],
    'GONZALEZ MAXINEZ DAVID JAIME': [
        'DISEÑO DE SISTEMAS DIGITALES (L)',
        'DISEÑO LOGICO (L)',
        'MICROPROCESADOR.Y MICROCONTROLAD.(L)',
        'ROBOTICA'
    ],
    'GONZALEZ PONCE ALEJANDRO RENE': ['PROCESAMIENTO DIGIT.IMAGENES'],
    'GOYTIA HERRERA MARCO INTI': ['MINERIA DE DATOS'],
    'GRADA HUERTA IVAN': ['INTRODUCCION A LA INGENIERIA EN COMPUTACION'],
    'GUERRERO SANTAMARIA EFREN': ['ADMINISTRACION DE PROYECTOS', 'HABILIDADES DIRECTIVAS'],
    'GUTIERREZ CASTILLO ALMA ROSA': ['EMPRENDIMIENTO 2', 'EMPRENDIMIENTO 3'],
    'GUTIERREZ LOPEZ FELIPE DE JESUS': ['PROGRAMACION MOVIL 1'],
    'GUTIERREZ OROZCO RICARDO ARTURO': ['COMPILADORES', 'SISTEMAS DE INFORMACION'],
    'HERNANDEZ AGUILAR CESAR ALBERTO': ['PROYECTO ESCUELA-INDUSTRIA'],
    'HERNANDEZ AUDELO LEOBARDO': ['SEGURIDAD INFORMATICA', 'TEMAS ESPECIALES DE SEGURidad INFORM'],
    'HERNANDEZ CABRERA JESUS': [
        'COMPUTADORAS Y PROGRAMACION',
        'DISEÑO Y ANALISIS DE ALGORITMOS',
        'ESTRUCTURA DE DATOS',
        'PROGRAMACION WEB 2'
    ],
    'HERNANDEZ CERVANTES LILIANA': ['GRAFICACION POR COMPUTADORA'],
    'HERNANDEZ CONTRERAS JUAN MANUEL': ['MICROPROCESADOR.Y MICROCONTROLAD.(L)'],
    'HERNANDEZ GALICIA SALOMON': ['CALCULO DIFERENCIAL E INTEGRAL'],
    'HERNANDEZ HERNANDEZ MARTIN': ['DISEÑO DE SISTEMAS DIGITALES (L)'],
    'HERNANDEZ LOPEZ SERGIO': ['ALGEBRA', 'ELECTRICIDAD Y MAGNETISMO (L)', 'PROBABILIDAD Y ESTADISTICA'],
    'ISLAS HERNANDEZ CLARA YAHAIRA': ['COMUNICACION'],
    'JUAREZ PALMA JOSE GIL': ['ECUACIONES DIFERENCIALES'],
    'JUAREZ ROBLES ELIZABETH': ['INTELIGENCIA ARTIFICIAL', 'LENGUAJES FORMALES-AUTOMATAS', 'MINERIA DE DATOS'],
    'LOPEZ CARRETO JUAN MANUEL': ['DISEÑO LOGICO (L)', 'DISPOSITIVOS ELECTRONICOS (L)'],
    'LOPEZ HERNANDEZ JORGE ARTURO': ['ADMINISTRACION SISTEMAS MULTIUSUAR', 'LAB REDES DE COMPUTADORAS I'],
    'LOZANO MENDEZ EFREN': [
        'DISEÑO DE SISTEMAS DIGITALES (L)',
        'DISEÑO LOGICO (L)',
        'INTERNET DE LAS COSAS',
        'MICROPROCESADOR.Y MICROCONTROLAD.(L)'
    ],
    'MARTINEZ ROMERO JONATHAN': [
        'ECUACIONES DIFERENCIALES',
        'GEOMETRIA ANALITICA',
        'METODOS NUMERICOS',
        'MICROPROCESADOR.Y MICROCONTROLAD.(L)'
    ],
    'MENDOZA GONZALEZ OMAR': ['BASES DE DATOS 2', 'MINERIA DE DATOS', 'SISTEMAS DE INFORMACION'],
    'MONDRAGON ESCOBAR ALFREDO': [
        'ADMINISTRACION DE PROYECTOS',
        'COMUNICACION',
        'EMPRENDIMIENTO 2',
        'PROYECTO ESCUELA-INDUSTRIA'
    ],
    'MONTERROSA ESCOBAR AMILCAR AMADO': ['INTELIGENCIA ARTIFICIAL'],
    'MORALES GONZALEZ JORGE CARLOS': ['METODOS NUMERICOS'],
    'MORALES PALAFOX EDGAR': ['INTELIGENCIA ARTIFICIAL'],
    'NAVARRO DIAZ RAMON': ['SEGURIDAD INFORMATICA'],
    'NERIA OROZCO ERIK DE JESUS': ['SEGURIDAD INFORMATICA'],
    'OCAMPO ALVAREZ ARTURO': ['MICROPROCESADOR.Y MICROCONTROLAD.(L)'],
    'OLIVER MORALES CARLOS': [
        'DISEÑO Y ANALISIS DE ALGORITMOS',
        'INTELIGENCIA ARTIFICIAL',
        'LENGUAJES FORMALES-AUTOMATAS'
    ],
    'ORDOÑEZ ROSALES MARTIN': ['BASES DE DATOS 1', 'COMPILADORES', 'TEMAS ESPECIALES DE BASES DE DATOS'],
    'ORTEGA NAVA CARLOS FERNANDO': ['DISPOSITIVOS ELECTRONICOS (L)'],
    'ORTIZ CORDERO GABRIEL': ['ALGEBRA', 'LENGUAJES FORMALES-AUTOMATAS', 'MATEMATICAS DISCRETAS'],
    'ORTIZ JIMENEZ MARIA ELENA': ['PROGRAMACION WEB 1'],
    'PALMA LOPEZ DANIEL FERNANDO': ['SEGURIDAD INFORMATICA'],
    'PARRALES CASTAÑEDA CARLOS ALBERTO': ['INTRODUCCION A LA INGENIERIA EN COMPUTACION'],
    'PATIÑO RODRIGUEZ RAMON': ['DISEÑO LOGICO (L)', 'GEOMETRIA ANALITICA'],
    'PELCASTRE RAMIREZ GLORICRUZ LUEVANO BLANCA ESTELAA SAMANTHA': [
        'CALCULO DIFERENCIAL E INTEGRAL',
        'PROBABILIDAD Y ESTADISTICA'
    ],
    'PEÑALOZA ROMERO ERNESTO': ['COMPUTADORAS Y PROGRAMACION', 'ESTRUCTURA DE DATOS'],
    'PEREZ GUZMAN ALEJANDRO': ['ALGEBRA LINEAL', 'ELECTRICIDAD Y MAGNETISMO (L)', 'METODOS NUMERICOS'],
    'PEREZ MEDEL MARCELO': ['DISEÑO Y ANALISIS DE ALGORITMOS'],
    'PEREZ MUÑOZ ANTONIO GERARDO': ['REDES DE COMPUTADORAS 1 (L)'],
    'PEREZ PAZ EDUARDO': ['PROGRAMACION WEB 1'],
    'PEREZ SANCHEZ HIRAM EMMANUEL': ['TEMAS ESPECIALES DE PROGRAMACION 2'],
    'PEREZ VALDES JOEL ALFREDO': ['SEMINARIO INGENIERIA EN COMPUTACION', 'TALLER DE CREATIVIDAD E INNOVACION', 'VINCULACION EMPRESARIAL'],
    'PICCINELLI BOCCHI GABRIELLA': ['ELECTRICIDAD Y MAGNETISMO (L)'],
    'QUINTERO CERVANTES JOSE MANUEL': ['LAB REDES DE COMPUTADORAS I', 'REDES DE COMPUTADORAS 1 (L)', 'TEMAS ESPECIALES DE REDES'],
    'QUIROZ ALMARAZ SERGIO': ['DISEÑO Y ANALISIS DE ALGORITMOS', 'REDES DE COMPUTADORAS 2'],
    'RAMIREZ CRUZ JOSE LUIS': ['DISEÑO LOGICO (L)'],
    'RAMIREZ LAZOS ESTEBAN': ['ALGEBRA', 'CALCULO DIFERENCIAL E INTEGRAL', 'METODOS NUMERICOS'],
    'RAMOS MARQUEZ JUAN CARLOS': ['COMPUTADORAS Y PROGRAMACION', 'PROGRAMACION WEB 2'],
    'REYES CRUZ ANA CLAUDIA': ['ADMINISTRACION DE PROYECTOS'],
    'REYES TECONTERO NORMA': ['EMPRENDIMIENTO 2', 'HABILIDADES DIRECTIVAS'],
    'RIVERO PICAZO MARIELA VIANEY': ['VINCULACION EMPRESARIAL'],
    'RODRIGUEZ GARCIA ARTURO': [
        'CALCULO DIFERENCIAL E INTEGRAL',
        'ECUACIONES DIFERENCIALES',
        'GEOMETRIA ANALITICA',
        'MATEMATICAS DISCRETAS'
    ],
    'ROMERO ANDALON JESUS ANGEL': ['ADMINISTRACION DE PROYECTOS', 'EMPRENDIMIENTO 1'],
    'ROMERO UGALDE MARTIN MANUEL': ['INTELIGENCIA ARTIFICIAL', 'SISTEMAS EXPERTOS'],
    'SALDAÑA ALDANA HECTOR': ['TEMAS ESPECIALES DE PROGRAMACION 2'],
    'SALGADO RODRIGUEZ JOSE FRANCISCO': [
        'GRAFICACION POR COMPUTADORA',
        'PROGRAMACION DE VIDEOJUEGOS 1',
        'PROGRAMACION DE VIDEOJUEGOS 2',
        'TEMAS ESPECIALES DE COMPUTACION 6'
    ],
    'SANCHEZ HERNANDEZ MIGUEL ANGEL': [
        'DISEÑO Y ANALISIS DE ALGORITMOS',
        'ESTRUCTURA DE DATOS',
        'MINERIA DE DATOS',
        'PROGRAMACION WEB 2',
        'PROGRAMACION ORIENTADA A OBJETOS'
    ],
    'SANCHEZ MORALES VICTOR MANUEL': ['CALCULO VECTORIAL'],
    'SANCHEZ SANCHEZ VICTOR MANUEL': [
        'COMPUTADORAS Y PROGRAMACION',
        'DISEÑO Y ANALISIS DE ALGORITMOS',
        'ESTRUCTURA DE DATOS',
        'LENGUAJES FORMALES-AUTOMATAS',
        'PROGRAMACION WEB 2'
    ],
    'SEGURA RAUDA MINERVA': ['ELECTRICIDAD Y MAGNETISMO (L)'],
    'SOBERANES JAIME ROBERTO MISAEL': ['BASES DE DATOS 1', 'BASES DE DATOS 2', 'SEGURIDAD INFORMATICA'],
    'SOLIS ALCANTAR EVERARDO': ['ALGEBRA LINEAL', 'GEOMETRIA ANALITICA'],
    'SUAREZ HERRERA ALEJANDRO': ['ELECTRICIDAD Y MAGNETISMO (L)'],
    'TORRES RODRIGUEZ GERARDO': [
        'LAB REDES DE COMPUTADORAS I',
        'REDES DE COMPUTADORAS 1 (L)',
        'REDES DE COMPUTADORAS 2',
        'TEMAS ESPECIALES DE REDES'
    ],
    'TORRES TORRES FAUSTO': ['PROBABILIDAD Y ESTADISTICA'],
    'UGALDE LOPEZ JUDITH': ['HABILIDADES DIRECTIVAS'],
    'VALENZUELA LOPEZ RODOLFO': ['TEMAS ESPECIALES DE COMPUTACION 1'],
    'VALENZUELA RAMOS JUAN GERMAN': ['TEMAS ESPECIALES DE COMPUTACION 2'],
    'VAZQUEZ MORALES RODOLFO': ['SEGURIDAD INFORMATICA', 'SISTEMAS OPERATIVOS'],
    'VEGA MUNGUIA ELIO': ['TEMAS ESPECIALES DE COMPUTACION 6'],
    'VELASCO AGUSTIN AARON': ['INTRODUCCION A LA INGENIERIA EN COMPUTACION', 'PROGRAMACION WEB 1', 'PROGRAMACION WEB 2', 'SISTEMAS DE INFORMACION'],
    'VERDE CRUZ ABEL': ['ELECTRICIDAD Y MAGNETISMO (L)'],
    'VERDUZCO RODRIGUEZ MARIANA': ['PROGRAMACION WEB 2', 'SEGURIDAD INFORMATICA', 'SISTEMAS DE INFORMACION'],
    'VIDAL CASTRO RICARDO ADOLFO': ['ADMINISTRACION DE PROYECTOS'],
    'VIEYRA REBOYO LUIS ARMANDO': ['ALGEBRA', 'GEOMETRIA ANALITICA', 'METODOS NUMERICOS'],
    'VILLANUEVA ORTEGA JUAN ANTONIO': ['TEMAS ESPECIALES DE COMPUTACION 3'],
    'ZUÑIGA VILLEGAS BENITO': ['INSTRUMENTACION Y CONTROL'],
}


# ===========================================
# BASE DE CONOCIMIENTO COMPLETA (PARTE 2)
# Grupos, grupos optativas, salones, horarios
# ===========================================

# ------------------------
# GRUPOS REGULARES
# ------------------------

grupos = {
    1107: 'Matutino', 1108: 'Matutino', 1109: 'Matutino',
    1157: 'Vespertino', 1158: 'Vespertino', 1159: 'Vespertino',

    1207: 'Matutino', 1208: 'Matutino',

    1257: 'Vespertino', 1258: 'Vespertino',

    1307: 'Matutino', 1308: 'Matutino', 1309: 'Matutino',
    1310: 'Matutino', 1311: 'Matutino',

    1357: 'Vespertino', 1358: 'Vespertino', 1359: 'Vespertino',
    1360: 'Vespertino',

    1407: 'Matutino', 1408: 'Matutino',

    1457: 'Vespertino',

    1507: 'Matutino', 1508: 'Matutino', 1509: 'Matutino',
    1510: 'Matutino', 1511: 'Matutino', 1512: 'Matutino',

    1557: 'Vespertino', 1558: 'Vespertino', 1559: 'Vespertino',
    1560: 'Vespertino', 1561: 'Vespertino',

    1607: 'Matutino', 1608: 'Matutino',

    1657: 'Vespertino', 1658: 'Vespertino',

    1707: 'Matutino', 1708: 'Matutino', 1709: 'Matutino',
    1710: 'Matutino', 1711: 'Matutino',

    1757: 'Vespertino', 1758: 'Vespertino', 1759: 'Vespertino',
    1760: 'Vespertino', 1761: 'Vespertino',

    1807: 'Matutino', 1808: 'Matutino',

    1857: 'Vespertino', 1858: 'Vespertino', 1859: 'Vespertino',

    1907: 'Matutino', 1908: 'Matutino', 1909: 'Matutino',
    1910: 'Matutino',

    1957: 'Vespertino', 1958: 'Vespertino',
    1959: 'Vespertino', 1960: 'Vespertino', 1961: 'Vespertino',
}

# ------------------------
# GRUPOS DE OPTATIVAS
# ------------------------

grupos_optativas = {
    1007: 'Matutino', 1008: 'Matutino', 1009: 'Matutino',
    1010: 'Matutino',

    1057: 'Vespertino', 1058: 'Vespertino', 1059: 'Vespertino',
    1060: 'Vespertino', 1061: 'Vespertino', 1062: 'Vespertino',
}

# ------------------------
# SALONES
# ------------------------

salones = [
    'A214', 'A215', 'A216', 'A8118', 'A8120', 'A8117', 'A8119',
    'A11201', 'A8121', 'A504', 'A205', 'A213', 'A211', 'A505',
    'A506', 'A507', 'A212', 'VIRTUAL', 'A203', 'A204', 'A325',
    'CCSAL6', 'A11202', 'A11203', 'CCSAL7', 'CCSAL1', 'A1023',
    'A11204', 'A11201', 'CCSAL9', 'CCSAL5', 'A11205', 'CLOUD'
]

# ------------------------
# HORARIOS (día, inicio, fin, turno)
# ------------------------

horarios = [
    # Lunes
    ('Lunes', 7.0, 8.3, 'Matutino'),
    ('Lunes', 8.3, 10.0, 'Matutino'),
    ('Lunes', 10.0, 11.3, 'Matutino'),
    ('Lunes', 11.3, 13.0, 'Matutino'),
    ('Lunes', 13.0, 14.3, 'Vespertino'),
    ('Lunes', 14.3, 16.0, 'Vespertino'),
    ('Lunes', 16.0, 17.3, 'Vespertino'),
    ('Lunes', 17.3, 19.0, 'Vespertino'),
    ('Lunes', 19.0, 20.3, 'Vespertino'),
    ('Lunes', 20.3, 22.0, 'Vespertino'),

    # Martes  
    ('Martes', 7.0, 9.0, 'Matutino'),
    ('Martes', 9.0, 11.0, 'Matutino'),
    ('Martes', 11.0, 13.0, 'Matutino'),
    ('Martes', 13.0, 15.0, 'Matutino'),
    ('Martes', 13.0, 15.0, 'Vespertino'),
    ('Martes', 15.0, 17.0, 'Vespertino'),
    ('Martes', 17.0, 19.0, 'Vespertino'),
    ('Martes', 19.0, 21.0, 'Vespertino'),

    # Miércoles
    ('Miercoles', 7.0, 8.3, 'Matutino'),
    ('Miercoles', 8.3, 10.0, 'Matutino'),
    ('Miercoles', 10.0, 11.3, 'Matutino'),
    ('Miercoles', 11.3, 13.0, 'Matutino'),
    ('Miercoles', 13.0, 14.3, 'Vespertino'),
    ('Miercoles', 14.3, 16.0, 'Vespertino'),
    ('Miercoles', 16.0, 17.3, 'Vespertino'),
    ('Miercoles', 17.3, 19.0, 'Vespertino'),
    ('Miercoles', 19.0, 20.3, 'Vespertino'),
    ('Miercoles', 20.3, 22.0, 'Vespertino'),

    # Jueves
    ('Jueves', 7.0, 9.0, 'Matutino'),
    ('Jueves', 9.0, 11.0, 'Matutino'),
    ('Jueves', 11.0, 13.0, 'Matutino'),
    ('Jueves', 13.0, 15.0, 'Matutino'),
    ('Jueves', 13.0, 15.0, 'Vespertino'),
    ('Jueves', 15.0, 17.0, 'Vespertino'),
    ('Jueves', 17.0, 19.0, 'Vespertino'),
    ('Jueves', 19.0, 21.0, 'Vespertino'),

    # Viernes
    ('Viernes', 7.0, 8.3, 'Matutino'),
    ('Viernes', 8.3, 10.0, 'Matutino'),
    ('Viernes', 10.0, 11.3, 'Matutino'),
    ('Viernes', 11.3, 13.0, 'Matutino'),
    ('Viernes', 13.0, 14.3, 'Vespertino'),
    ('Viernes', 14.3, 16.0, 'Vespertino'),
    ('Viernes', 16.0, 17.3, 'Vespertino'),
    ('Viernes', 17.3, 19.0, 'Vespertino'),
    ('Viernes', 19.0, 20.3, 'Vespertino'),
    ('Viernes', 20.3, 22.0, 'Vespertino'),

    # Sábado
    ('Sabado', 7.0, 11.0, 'Matutino'),
    ('Sabado', 9.0, 13.0, 'Matutino'),
    ('Sabado', 11.0, 15.0, 'Vespertino'),
]
